site_name: Standard ASR

theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - header.autohide
    # - navigation.tabs 
  favicon: assets/branding/icon.png
  font:
    text: Noto Sans
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - privacy
  - offline

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Introduction: intro.md
  - Mission: mission.md
  - Goals: goals.md
  - Roadmap: roadmap.md
  - App Developers:
      - Discover & Use: for_app_dev/discover_and_use.md
  - ASR Developers:
      - Adapt an Engine: for_asr_dev/adapting_engine.md
      - Properties: for_asr_dev/properties.md
      - Plugin Entrypoints: for_asr_dev/plugin_entrypoints.md
  - Specs:
      - Protocol: spec/protocol.md
      - Results: spec/results.md
      - Options: spec/options.md
      - Properties: spec/properties.md
      - Features: spec/features.md
      - Streaming: spec/streaming.md
      - CLI: spec/cli.md
      - API: spec/api.md
      - Download Policy: spec/download-policy.md
